import os
import csv

off_data = 'resultats-par-niveau-dpt-t1-france-entiere.csv'
#nbRowMax = 107
#nbColMax = 89

def clear_votersDEP_csv():
    """
        Deletes all files generated by generate_voters_by_department()
    """
    with open(off_data, 'r') as csvfile:
        reader = csv.reader(csvfile)
        next(reader)
        for row in reader:
            dep_code = row[0]
            filename = "voters" + dep_code + ".csv"
            if(os.path.exists(filename) and os.path.isfile(filename)):
                os.remove(filename)
                print("file for departement " + dep_code + " deleted")
            else:
                print("no csv file to delete found for departement " + dep_code)


clear_votersDEP_csv()